### ISSUE TITLE
Drop Mobile Wireless Data

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#100]
This was a recommendation from @ZachBeck. I would love to do this. It would simplify the app and data. I'm going to go with it. @nathankota Do you have any issues with this?

**Comment by nathankota** [comment]
Initial thoughts are that I do not have any issues with it, but I would also like to get GOED's blessing; however, they might not care too much. Should I ask them now, or should we wait until we share the test app with them and drop it on them then, with some explanation/reasoning?

**Comment by ZachBeck** [comment]
I wonder if it would be worth keeping mobile wireless for 5g speeds.

**Comment by nathankota** [comment]
IIRC in my most recent communication with Rebecca, she wasn't too keen on the idea of eliminating mobile wireless.

**Comment by ZachBeck** [comment]
Bummer. I think wireless should have a lower cutoff for speeds like other broadband since you can't do much with 3g and below. Maybe she could be persuaded to just show wireless with speeds that are useful (4g, 5g)

**Comment by nathankota** [comment]
That's a good compromise. I say we pursue it.

**Comment by stdavis** [comment]
@ZachBeck: would the def query for this be `TransTech <> 80 OR MAXADDOWN > 14`? Or what's a good cut-off that would exclude 3g speeds?

**Comment by ZachBeck** [comment]
I think that would work. Right now I have 4g at 30ish, 3g at 3, and everything else at 1.5. They make it hard since it's a wireless technology rather than a speed.

**Comment by stdavis** [comment]
OK. I've got the new def query in my script that I'm working with. I'm going to close this issue since we aren't going to drop mobile wireless after all.
