### ISSUE TITLE
Missing Provider Results after filtering

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#117]
From Bert:
>weird bb map behavior

>map shows coverage but map click does not return provider

![image](https://user-images.githubusercontent.com/1326248/101090458-ec7c1c80-3573-11eb-8812-59cce83a85de.png)

**Comment by stdavis** [comment]
I believe that this is caused by missing records in the providers table. @ZachBeck Can you help fill in the missing rows?
![image](https://user-images.githubusercontent.com/1326248/101091982-277f4f80-3576-11eb-874e-b01acbda7bd4.png)

**Comment by ZachBeck** [comment]
I think I need to delete those from the service areas. I think Vivint is gone and Syringa is business fiber.

**Comment by stdavis** [comment]
@ZachBeck Any update on this?

**Comment by ZachBeck** [comment]
They are gone now.

**Comment by stdavis** [comment]
/remind me to check the app in two days

**Comment by stdavis** [comment]
Looks good, @ZachBeck. Thanks for the fix!
