### ISSUE TITLE
Setup Firebase DNS

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#129]
prod: `broadband.ugrc.utah.gov` - `ut-dts-agrc-broadband-prod`
stage: `broadband.dev.utah.gov` - `ut-dts-agrc-broadband-dev`

Please request these new domains and point at their associated firebase projects.

**Comment by nathankota** [comment]
INC1509822

**Comment by nathankota** [comment]
Still a WIP

**Comment by nathankota** [comment]
complete
