### ISSUE TITLE
Add 20 to download speed slider

### ISSUE THREAD

**Issue by nathankota** [agrc/broadband#131]
Criteria for the new grant offered by the GOEO Broadband Office will increase interest in knowing where service is provided at 100/20 and 25/3. Please add a stopping point of 20 for the download speed slider.

![image](https://user-images.githubusercontent.com/15659642/135901107-9c6ace86-b753-4d91-ae71-d58737987ab2.png)

**Comment by stdavis** [comment]
I've pushed this to https://broadband.dev.utah.gov/. Please review and let me know what you think.

**Comment by nathankota** [comment]
Looks good to me, thank you! @ZachBeck could you do a quick spot check against your experience builder data set for 100/20 to make sure they agree, before we schedule for production?

**Comment by ZachBeck** [comment]
Looks good to me too

**Comment by stdavis** [comment]
@nathankota So am I good to push this to production?
