### ISSUE TITLE
Use new GOUtah logo 

### ISSUE THREAD

**Issue by nathankota** [agrc/broadband#132]
Replace the GOED logo with the dark GOUtah logo [here](https://drive.google.com/drive/folders/1hZotSAVRGy0Wed-73DUkLuR9jNVJd6On). Keep the link from the logo to business.utah.gov/broadband.

**Comment by stdavis** [comment]
@nathankota: This has been pushed to dev: https://broadband.dev.utah.gov/

Please take a look and let me know if we are good to push to prod.

**Comment by nathankota** [comment]
Looks good, please push to prod at your convenience.
