### ISSUE TITLE
Smaller screen layout is broken

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#22]
Probably from upgrading boilerplate.
![image](https://cloud.githubusercontent.com/assets/1326248/5304618/c3bac882-7bb1-11e4-9f84-92b4f96c244e.png)

**Comment by brigsz** [comment]
I poke around resizing my screen and tried it out on an iPad.  I was not able to reproduce this issue.  Did you already fix it?

**Comment by stdavis** [comment]
This is a regression bug that shows up in the new version on the test server. No, I haven't fixed it yet.

**Comment by brigsz** [comment]
I couldn't reproduce it...but I wasn't sure how

**Comment by stdavis** [comment]
Open it on the test server: http://test.mapserv.utah.gov/broadband/

On Mon, Jan 26, 2015 at 1:07 PM, Matt Peters <notifications@github.com>
wrote:

> I couldn't reproduce it...but I wasn't sure how
>
>
> On Mon, Jan 26, 2015 at 1:06 PM, Scott Davis <notifications@github.com>
> wrote:
>
> > This is a regression bug that shows up in the new version on the test
> > server. No, I haven't fixed it yet.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/agrc/broadband/issues/22#issuecomment-71528114>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/broadband/issues/22#issuecomment-71528376>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>
