### ISSUE TITLE
Print to pdf

### ISSUE THREAD

**Issue by brigsz** [agrc/broadband#23]
I am unable to see the Print button on the Broadband map.  It seems like the work was completed.  Print to PDF is #4.  Was it decided this should not be done? Or did it just become a nightmare?

**Comment by stdavis** [comment]
It's in the code base and on the test server at http://test.mapserv.utah.gov/broadband/. Not sure that I got the go ahead to push that version to production.

**Comment by brigsz** [comment]
oh, okay, I will check into it

**Comment by stdavis** [comment]
Will need to fix #22 before it gets pushed. Let me know where it falls in
the priority list.

On Mon, Jan 26, 2015 at 1:05 PM, Matt Peters <notifications@github.com>
wrote:

> oh, okay, I will check into it
>
>
> On Mon, Jan 26, 2015 at 1:04 PM, Scott Davis <notifications@github.com>
> wrote:
>
> > It's in the code base and on the test server at
> > http://test.mapserv.utah.gov/broadband/. Not sure that I got the go
> ahead
> > to push that version to production.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/agrc/broadband/issues/23#issuecomment-71527833>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/broadband/issues/23#issuecomment-71527949>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by stdavis** [comment]
This is working now on the test server.
