### ISSUE TITLE
schedule update script to run nightly

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#24]
It is run manually currently.

**Comment by jpechmann** [comment]
Most days there would not be an update, do you think that matters?

**Comment by stdavis** [comment]
No. It doesn't hurt to have it check for changes every night.

On Mon, Jun 22, 2015 at 9:40 AM, jpechmann <notifications@github.com> wrote:

> Most days there would not be an update, do you think that matters?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/broadband/issues/24#issuecomment-114157175>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by jpechmann** [comment]
Then sure. Lets do it so its automated. Can you update both the residential map and locate.ut.gov in the same process?

**Comment by stdavis** [comment]
locate.utah.gov is pointed at the same database as this project for
broadband data. So yes, it will be updated at the same time.

On Mon, Jun 22, 2015 at 10:00 AM, jpechmann <notifications@github.com>
wrote:

> Then sure. Lets do it so its automated. Can you update both the
> residential map and locate.ut.gov in the same process?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/broadband/issues/24#issuecomment-114164240>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by jpechmann** [comment]
Great!
