### ISSUE TITLE
Link to Broadband Outreach Center

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#29]
As a user, I'd like to be able to link to other mapping resources of the Broadband Outreach Center.

Link to locate.utah.gov and map gallery.

Map Gallery: This will be under the map drop down in upper right
Locate Link: This is TBD. Will be prominent.

Estimate: 2hrs

**Comment by stdavis** [comment]
@jpechmann What's the URL to the map gallery? Also need to know where you want the link to locate.utah.gov. There is already a link to it under the map menu. I'm guessing that's not prominent enough?

**Comment by jpechmann** [comment]
Map Gallery: http://broadband.utah.gov/map-gallery/

**Comment by stdavis** [comment]
I'll wait to do anything on this until @jpechmann makes any changes to the menu's on the home page.

**Comment by jpechmann** [comment]
Okay, sounds good. We also need to add a "Home" tab on the left of the other tabs and unlink the logo to the home page that is in the upper left.
