### ISSUE TITLE
Report Data Currency

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#30]
As a user, I'd like to know the currency date of the broadband data.

There will be a last "reported by" date at the bottom of the pop up under Provider Results on the left. 	

This will be a new date field in the database.

Estimate: 5hrs

**Comment by stdavis** [comment]
@jpechmann Would this be the `StartDate` field? Or has this field not been added to the database yet?

**Comment by stdavis** [comment]
Waiting for new database schema.

**Comment by jpechmann** [comment]
UBBMAP.UBBADMIN.BB_Service_Fixed_test. The data currency field is "LastVerified".
