### ISSUE TITLE
Telcom Provider Result

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#31]
As a user, I'd like to know what telcom boundary I clicked on.

The telecom provider in a clicked on location will return at the bottom of the Provider Results listed on the left.

This data is in the SGID.

Estimate: 5hrs

**Comment by stdavis** [comment]
@jpechmann What is the name of the dataset in SGID10?
![image](https://cloud.githubusercontent.com/assets/1326248/12203199/f262319c-b5ea-11e5-97bb-7ce2b85e9432.png)

I think that the second one is the newer one, isn't it? Not sure.

**Comment by jpechmann** [comment]
@stdavis Good question! It is SGID10.UTILITIES.RuralTelcomBoundaries.

**Comment by stdavis** [comment]
`telcom` branch closes this issue assuming that @BGranberg is OK with @jpechmann proposal above.
