### ISSUE TITLE
Technology Type Reclassification

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#33]
Organize Technology Type by Wireline, Fixed Wireless and Mobile Wireless under checkboxes on right

Under the Technology Type, there will be three categories: wireline, fixed wireless, and mobile wireless. Wireline will have cable, DSL, and fiber under it, the other two will just have one checkbox per category.	

Symbology on the map will be based on the 3 categories.

Estimate: 5hrs

**Comment by stdavis** [comment]
@jpechmann What were we thinking for the symbology for this?

**Comment by stdavis** [comment]
de55a68 is half of this issue. Waiting to start on the other half for the new data schema and symbology.

**Comment by jpechmann** [comment]
@stdavis I've created a small database with the new schema: UBBMAP.UBBADMIN.BB_Service_Fixed_test. It has 2 different providers (CenturyLink and Strata), and 3 different transmission technologies. Transmission technology is still a domain value. There are various down and up speed values in mbps.
