### ISSUE TITLE
Speed Sliders Data Change

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#34]
Speed sliding bars will read a numerical value and put them into a speed tier.

The sliding bar will have speed tiers defined by the Broadband Outreach Center.	

This is just a data change the sliding bar on the map will remain the same.

Estimate: 2hrs

**Comment by stdavis** [comment]
@jpechmann I assume that this change has not been made on the data side yet?

**Comment by jpechmann** [comment]
Test database: UBBMAP.UBBADMIN.BB_Service_Fixed_test. There aren't a huge range of speeds in there yet, but hopefully it is good enough to start.
