### ISSUE TITLE
Resellers link is broken

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#41]
@jpechmann What URL should this link go to?
![image](https://cloud.githubusercontent.com/assets/1326248/12204459/95730efa-b5f1-11e5-9b93-df99e27cb4a5.png)

Currently it's pointed at http://broadband.utah.gov/resellers/ which is broken.

**Comment by jpechmann** [comment]
Here it is: http://broadband.utah.gov/providers/#resellers.

**Comment by stdavis** [comment]
Thanks!
