### ISSUE TITLE
Update locate.utah.gov with new residential coverage schema

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#42]
Related to #33

**Comment by stdavis** [comment]
Waiting for new database schema to be production-ready.

**Comment by jpechmann** [comment]
New database is production ready: UBBMAP.UBBADMIN.BB_Service.

**Comment by stdavis** [comment]
Closed with https://github.com/agrc/bb-econ/commit/cc7d57065a0a7d2fbf4eff07b0abaa8ffc3b7eb7.
