### ISSUE TITLE
Basemaps do not show up in printed pdf (medium low)

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#45]
Probably because the quad word doesn't work coming from the server. Maybe have to hack the map object sent to the server to insert another quad word? Or maybe Rick can make a quad word that will work for both?

Any ideas @steveoh?

**Comment by stdavis** [comment]
@rkelson:
I've got a problem that I'm wondering if you can help with. The issue is that basemaps from discover are not showing up when we print to pdf from web apps. The cause is because the pdf is generated on the server and not in the browser. So the request for the discover web apps comes from an ip address instead of a domain name. Is there any way that you can make a quad word work for both an ip address and domain name? If not there are other options but this would be the most simple solution.

**Comment by rkelson** [comment]
I can make a new quad word that should work for both an IP and Domain but it will have to be a new quad-word as our request for the ability to edit existing RegExs has fallen on deaf ears.
What was the User and/or quad-word? What is the IP to use?

**Comment by stdavis** [comment]
The quad word is "reserve-tactic-cricket-spider" which I believe is the
mapserv user. Please add an additional quad word to this account that has
the same regex as reserve-tactic-cricket-spider but also includes this
IP: 204.113.19.47. Thanks!

On Mon, Jan 25, 2016 at 10:58 AM, Rick Kelson <notifications@github.com>
wrote:

> I can make a new quad word that should work for both an IP and Domain but
> it will have to be a new quad-word as our request for the ability to edit
> existing RegExs has fallen on deaf ears.
> What was the User and/or quad-word? What is the IP to use?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/broadband/issues/45#issuecomment-174603414>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@SThomasDavis <https://twitter.com/SThomasDavis>

**Comment by steveoh** [comment]
Wouldn't it be the IP of the server printing, so gisapp1 and 2?

**Comment by stdavis** [comment]
I assumed that it would be the external ip address?

**Comment by stdavis** [comment]
@rkelson: @steveoh agrees that it's likely the external ip address so give 204.113.19.47 a try and we'll see if it works. Thanks!

**Comment by steveoh** [comment]
We were not understanding the discover appliance correctly. Both host and referer are based on the referer header. One accepts a regex and the other does not.

For this to work for printing we will need to make a proxy printing service that take the same arguments as the arcgis server one and replaces any quad word with an open one we choose for the server. It will then proxy the request to the default print service and return the result. We would only need to change the url in our configs that point to the print service to make this work once the print proxy is created.

**Comment by stdavis** [comment]
https://github.com/agrc/print-proxy is the solution for this issue
