### ISSUE TITLE
Lite Basemap Changes

### ISSUE THREAD

**Issue by jpechmann** [agrc/broadband#46]
Add populated areas to lite basemap at coarse scales... maybe to level 11. 

Adjacent states in lite base map get a darker color to give a spotlight approach to Utah.

**Comment by jpechmann** [comment]
Temporary fix, make surrounding states gray in lite basemap- K:\AGRC Projects\BroadbandOutreachCenter\Projects\ResidentialMapV2. The gray to use is on the mask. 

I'll create a separate issue for pop areas, since that won't be immediately incorporated into the lite basemap.

**Comment by stdavis** [comment]
So is what you are looking for?
![image](https://cloud.githubusercontent.com/assets/1326248/12516663/da22cb62-c0eb-11e5-82af-4526c081f7cb.png)

**Comment by BGranberg** [comment]
I would knock the adjacent state labels down so that they are less prominent....i would suggest moving there gray level closer to the fill for those states

**Comment by stdavis** [comment]
Here's what I came up with. We can refine it more next week but wanted to get something caching over the weekend.
![image](https://cloud.githubusercontent.com/assets/1326248/12525507/f735285e-c121-11e5-9d04-7f959c85e389.png)

**Comment by stdavis** [comment]
I've pointed the test version of the app temporarily at the caching server for this service.

**Comment by jpechmann** [comment]
Aaron is working on a new surrounding gray.

**Comment by stdavis** [comment]
Newest gray color: 808080

Caching was kicked off this afternoon...

**Comment by stdavis** [comment]
From @BGranberg:
>We decided to keep the surrounding states in the lite cache white, as-is for now
