### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by jpechmann** [agrc/broadband#51]
Header will have title in the middle, and BOC logo in the upper left. No "home" menu item... (sorry!). Logo will link to the home page. 

[Residential Map Title Logo Mockup.pdf](https://github.com/agrc/broadband/files/104084/Residential.Map.Title.Logo.Mockup.pdf)

**Comment by jpechmann** [comment]
Kelleigh will send logo to use in the upper left. 

The title should match the same font as Locate's title. The residential map title is a bit smaller font size, bolded, and gray. Use slide number 2 in this gdoc as a guide- https://docs.google.com/a/utah.gov/presentation/d/1QU16xJ9t1jav0nXpG2PZKadIkBz6gP7YgTNUnwWJHOA/edit?usp=sharing.

Also, both the residential map title and locate title should be proper case.

**Comment by BGranberg** [comment]
Header logos files are now at: https://drive.google.com/drive/folders/0BxoOAQyOvGgaTHlNcTRyN0tPTTQ and shared to stdavis

**Comment by stdavis** [comment]
@jpechmann: Like this? New logo (with link added back), added title and removed home button.

![image](https://cloud.githubusercontent.com/assets/1326248/12654370/e2205b76-c5b0-11e5-9c84-03a114ab0f22.png)

**Comment by stdavis** [comment]
Here's the final product: http://quick.as/XGd8tBbx5
