### ISSUE TITLE
Default colors

### ISSUE THREAD

**Issue by BGranberg** [agrc/broadband#67]
can we set the default position on the sliders to looks like this:
http://i.imgur.com/ypGkTSZ.png

can we also set the default on map load to 3 Mbps???

**Comment by stdavis** [comment]
@BGranberg: So you want it to load like this by default?
![image](https://cloud.githubusercontent.com/assets/1326248/12686100/318e2e3e-c685-11e5-9d49-f1f19c8b9dce.png)

**Comment by jpechmann** [comment]
Hey, upload default needs to be 0.7.

Thanks!

**Comment by stdavis** [comment]
So like this?
![image](https://cloud.githubusercontent.com/assets/1326248/12688982/078a1a00-c697-11e5-92a6-00df51d98ce7.png)

**Comment by jpechmann** [comment]
Yup! Thank you.
