### ISSUE TITLE
Update Look and Feel to match broadband.utah.gov

### ISSUE THREAD

**Issue by stdavis** [agrc/broadband#87]
Looks like they've done a design update.
![image](https://user-images.githubusercontent.com/1326248/36118489-75b934e4-0ffa-11e8-9659-ea23065c9732.png)
![image](https://user-images.githubusercontent.com/1326248/36118496-7c46fa6c-0ffa-11e8-80a9-6413a8503acc.png)

**Comment by stdavis** [comment]
And now they've done another design update since this issue was opened. :)
![image](https://user-images.githubusercontent.com/1326248/70453397-e8ebad80-1a65-11ea-9714-82fb57829e3f.png)

**Comment by nathankota** [comment]
And yet another update, as they have brought the broadband site into the GOED website at https://business.utah.gov/broadband/

**Comment by stdavis** [comment]
Maybe trying to match their look and feel will always be a game of cat and mouse. Maybe we just go with something generic that's not specific to their design.

**Comment by nathankota** [comment]
What about similar design elements to locate.utah.gov, which we have more control over, or do we want to keep them distinct?

**Comment by stdavis** [comment]
Might be good to have a different design just to make sure that people don't confuse the two.
