### ISSUE TITLE
Report a Problem not working

### ISSUE THREAD

**Issue by nathankota** [agrc/broadband#91]
The "Report a Problem" button does not allow users to "Send" an issue. 

![image](https://user-images.githubusercontent.com/15659642/64960255-32a26e80-d850-11e9-8b0d-2870b959da4d.png)

**Comment by stdavis** [comment]
Duplicate of #83

**Comment by stdavis** [comment]
https://github.com/agrc/SendEmailService/issues/9

**Comment by stdavis** [comment]
This has been fixed.
